import { Footer } from "@/lib/components/Footer";
import { NavBar } from "@/lib/components/Navbar";
import { ClerkProvider } from "@clerk/nextjs";
import { Theme } from "@radix-ui/themes";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`antialiased`}>
          <Theme accentColor="orange" radius="full">
            <main className="min-h-svh flex flex-col">
              <header>
                <NavBar />
              </header>
              <div className="flex-1">{children}</div>
              <Footer />
            </main>
          </Theme>
        </body>
      </html>
    </ClerkProvider>
  );
}
